// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me: dynamic(() => import("./AboutMe")),
  content_index: dynamic(() => import("./ContentIndex")),
  hero: dynamic(() => import("./Hero")),
  learning_next: dynamic(() => import("./LearningNext")),
  learning_page: dynamic(() => import("./CurrentlyLearning")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
